---
#patch-node.yml

- name: debug
  debug:
    msg: Working on node "{{ item | json_query("status.addresses[?type=='Hostname'].address | [0]") | replace('\"','')  }}"

- name: Mark node "{{ item | json_query("status.addresses[?type=='Hostname'].address | [0]") }}" as unschedulable.
  kubernetes.core.k8s_drain:
    state: cordon
    name: "{{ item | json_query(\"status.addresses[?type=='Hostname'].address | [0]\") }}"

- name: Drain node "{{ item | json_query("status.addresses[?type=='Hostname'].address | [0]") }}"
  kubernetes.core.k8s_drain:
    state: drain
    name: "{{ item | json_query(\"status.addresses[?type=='Hostname'].address | [0]\") }}"
    delete_options:
      force: yes

- name: Install all security, critical, and rollup updates without a scheduled task
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
    reboot_timeout: 3600
  delegate_to: "{{ item | json_query(\"status.addresses[?type=='ExternalIP'].address | [0]\") }}"

# A set of task needs to go here to run the patching cycle, then reboot node and wait for node to be back on line

- name: Mark node "{{ item | json_query("status.addresses[?type=='Hostname'].address | [0]") }}" as schedulable.
  kubernetes.core.k8s_drain:
    state: uncordon
    name: "{{ item | json_query(\"status.addresses[?type=='Hostname'].address | [0]\") }}"
